const dictionaryData = [
    { word: "Alay", meaning: "Anak Layangan (berlebihan, norak)", sentence: "Jangan terlalu alay deh, biasa saja gayanya." },
    { word: "Ambyar", meaning: "Hancur berkeping-keping (biasanya tentang perasaan)", sentence: "Hatiku ambyar setelah mendengar kabar itu." },
    { word: "Baper", meaning: "Bawa Perasaan (mudah tersinggung/terharu)", sentence: "Jangan baper, dia cuma bercanda kok." },
    { word: "Barbar", meaning: "Tidak beraturan / nekat", sentence: "Main game-nya jangan barbar, santai saja." },
    { word: "Bestie", meaning: "Sahabat dekat", sentence: "Nanti kita jalan-jalan ya, bestie." },
    { word: "Bokek", meaning: "Tidak punya uang", sentence: "Akhir bulan nih, lagi bokek banget." },
    { word: "Bucin", meaning: "Budak Cinta (tergila-gila pada pasangan)", sentence: "Dia jadi bucin banget sejak pacaran sama kamu." },
    { word: "Cans", meaning: "Cantik", sentence: "Wah, hari ini kamu kelihatan cans banget!" },
    { word: "Caper", meaning: "Cari Perhatian", sentence: "Anak itu suka caper di depan guru." },
    { word: "Cuan", meaning: "Untung / Uang", sentence: "Semoga jualan hari ini dapat banyak cuan." },
    { word: "Curcol", meaning: "Curhat Colongan", sentence: "Lagi rapat malah curcol masalah pribadi." },
    { word: "Fix", meaning: "Pasti / Sudah ditentukan", sentence: "Jadwal liburan kita sudah fix ya." },
    { word: "FOMO", meaning: "Fear Of Missing Out (takut ketinggalan tren)", sentence: "Dia beli itu cuma karena FOMO, bukan butuh." },
    { word: "Gabut", meaning: "Gaji Buta (bosan, tidak ada kerjaan)", sentence: "Aku lagi gabut nih, temani ngobrol dong." },
    { word: "Gaje", meaning: "Gak Jelas", sentence: "Ceritanya gaje banget, aku jadi bingung." },
    { word: "Gans", meaning: "Ganteng", sentence: "Cowok itu gans tapi sombong." },
    { word: "Garing", meaning: "Tidak lucu (tentang lelucon)", sentence: "Jokes bapak-bapak itu kadang garing." },
    { word: "Gemoy", meaning: "Gemas", sentence: "Kucingmu gemoy banget, pengen cubit." },
    { word: "Gercep", meaning: "Gerak Cepat", sentence: "Kalau ada diskon harus gercep biar kebagian." },
    { word: "Ghosting", meaning: "Menghilang tanpa kabar", sentence: "Kenapa dia ghosting setelah kencan pertama?" },
    { word: "Halu", meaning: "Halusinasi (berkhayal tinggi)", sentence: "Jangan halu bisa nikah sama artis Korea." },
    { word: "Healing", meaning: "Proses penyembuhan / Liburan", sentence: "Aku butuh healing ke pantai akhir pekan ini." },
    { word: "Insecure", meaning: "Tidak percaya diri", sentence: "Melihat prestasinya bikin aku jadi insecure." },
    { word: "Japri", meaning: "Jalur Pribadi (chat personal)", sentence: "Nanti detailnya aku japri ya." },
    { word: "Julid", meaning: "Iri hati / suka berkomentar negatif", sentence: "Netizen jangan suka julid di kolom komentar." },
    { word: "Kepo", meaning: "Ingin tahu urusan orang lain", sentence: "Kamu kepo banget sih sama masalah dia." },
    { word: "Kudet", meaning: "Kurang Update (ketinggalan info)", sentence: "Makanya baca berita biar nggak kudet." },
    { word: "Kuper", meaning: "Kurang Pergaulan", sentence: "Jangan jadi kuper, ayo bergaul sama teman-teman." },
    { word: "Kuy", meaning: "Yuk (ajakan)", sentence: "Kuy berangkat sekarang mumpung belum macet." },
    { word: "Lebay", meaning: "Berlebihan", sentence: "Reaksinya lebay banget, padahal cuma luka kecil." },
    { word: "Legit", meaning: "Asli / Keren banget / Enak", sentence: "Rasa kue ini beneran legit." },
    { word: "Mabar", meaning: "Main Bareng (biasanya game)", sentence: "Nanti malam mabar Mobile Legends yuk." },
    { word: "Mager", meaning: "Malas Gerak", sentence: "Hari Minggu bawaannya mager, pengen rebahan aja." },
    { word: "Mantul", meaning: "Mantap Betul", sentence: "Masakan ibu emang mantul rasanya." },
    { word: "Modus", meaning: "Modal Dusta (ada udang di balik batu)", sentence: "Dia baik cuma karena modus mau pinjam uang." },
    { word: "Ngab", meaning: "Bang (kebalikan)", sentence: "Woy ngab, mau kemana lu?" },
    { word: "Nobar", meaning: "Nonton Bareng", sentence: "Ada acara nobar final Piala Dunia di kafe." },
    { word: "Otw", meaning: "On The Way (sedang di jalan)", sentence: "Tunggu bentar, aku sudah otw nih." },
    { word: "Pansos", meaning: "Panjat Sosial", sentence: "Dia cuma pansos sama artis itu biar terkenal." },
    { word: "Pewe", meaning: "Posisi Wenak (nyaman)", sentence: "Udah pewe di sofa, males bangun." },
    { word: "PHP", meaning: "Pemberi Harapan Palsu", sentence: "Hati-hati, cowok itu terkenal tukang PHP." },
    { word: "Rebahan", meaning: "Tidur-tiduran santai", sentence: "Hobi kaum milenial adalah rebahan." },
    { word: "Receh", meaning: "Selera humor rendah / murah", sentence: "Aku ketawa karena jokes receh dia." },
    { word: "Rempong", meaning: "Ribet / Repot", sentence: "Jangan bawa barang banyak-banyak, nanti rempong." },
    { word: "Sabi", meaning: "Bisa (kebalikan)", sentence: "Sabi lah kita gas ke puncak besok." },
    { word: "Salty", meaning: "Kesal / Nyinyir", sentence: "Dia jadi salty karena kalah main game." },
    { word: "Santuy", meaning: "Santai", sentence: "Hadapi masalah dengan santuy." },
    { word: "Savage", meaning: "Sadis / Keren banget", sentence: "Balasan chat-nya savage banget." },
    { word: "Sotoy", meaning: "Sok Tahu", sentence: "Jangan sotoy kalau tidak tahu faktanya." },
    { word: "Spill", meaning: "Ungkapkan / Ceritakan", sentence: "Spill dong siapa pacar barumu." },
    { word: "Woles", meaning: "Slow (santai)", sentence: "Woles aja, waktu kita masih banyak kok." },
    { word: "YOLO", meaning: "You Only Live Once (hidup cuma sekali)", sentence: "Beli aja tiket konsernya, YOLO!" }
];

// Expose data globally if loaded via script tag, or module export
if (typeof module !== 'undefined' && module.exports) {
    module.exports = dictionaryData;
} else {
    window.dictionaryData = dictionaryData;
}
